/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.viit.tnp.common;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class EditProfileJframe extends javax.swing.JFrame {

    Connection conn = MySqlConnect.getConnection();
    PreparedStatement pst = null;
    ResultSet rs = null;

    Integer pid;

    public EditProfileJframe(Integer p_id) throws SQLException {
        initComponents();
        setDefaultCloseOperation(EditProfileJframe.HIDE_ON_CLOSE);
        pid = p_id;
        display_person();
    }

    public void display_person() throws SQLException {
        String selectSQL = "SELECT fname,lname,email,dob,phone,gender,city,"
                + "street,flat,pincode from person where p_id=" + pid;
        PreparedStatement ps = conn.prepareStatement(selectSQL);
        ResultSet rs = ps.executeQuery();
        try {
            while (rs.next()) {
                labelFirstName.setText(rs.getString("fname"));
                labelLastName.setText(rs.getString("lname"));
                jTextField_city.setText(rs.getString("city"));
                jTextField_email.setText(rs.getString("email"));
                jTextField_flat.setText(rs.getString("flat"));
                jTextField_phone.setText(rs.getString("phone"));
                jTextField_street.setText(rs.getString("street"));
                jTextField_pincode.setText(rs.getString("pincode"));

            }
        } catch (SQLException e1) {
            e1.printStackTrace();
        } finally {
            ps.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_city = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_street = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_flat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_pincode = new javax.swing.JTextField();
        labelFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        loginButtonPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit profile");

        jPanel2.setBackground(new java.awt.Color(37, 46, 65));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name : ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 50, 150, 15);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 90, 111, 22);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile Number : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 140, 155, 22);

        jTextField_phone.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_phone.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_phone.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_phone.setBorder(null);
        jTextField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phoneActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_phone);
        jTextField_phone.setBounds(220, 140, 210, 30);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 200, 60, 22);

        jTextField_email.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_email.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_email.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_email.setBorder(null);
        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_email);
        jTextField_email.setBounds(220, 190, 210, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("City : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 260, 54, 22);

        jTextField_city.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_city.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_city.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_city.setBorder(null);
        jPanel2.add(jTextField_city);
        jTextField_city.setBounds(220, 260, 210, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Street :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 330, 67, 22);

        jTextField_street.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_street.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_street.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_street.setBorder(null);
        jPanel2.add(jTextField_street);
        jTextField_street.setBounds(220, 330, 210, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Flat No.:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 400, 75, 22);

        jTextField_flat.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_flat.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_flat.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_flat.setBorder(null);
        jTextField_flat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_flatActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_flat);
        jTextField_flat.setBounds(220, 400, 210, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pincode : ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 470, 87, 22);

        jTextField_pincode.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_pincode.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_pincode.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_pincode.setBorder(null);
        jTextField_pincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pincodeActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_pincode);
        jTextField_pincode.setBounds(220, 460, 210, 30);

        labelFirstName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelFirstName.setForeground(java.awt.Color.white);
        labelFirstName.setText("jLabel4");
        jPanel2.add(labelFirstName);
        labelFirstName.setBounds(210, 50, 63, 22);

        labelLastName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelLastName.setForeground(java.awt.Color.white);
        labelLastName.setText("jLabel9");
        jPanel2.add(labelLastName);
        labelLastName.setBounds(210, 90, 63, 22);

        jSeparator2.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(null);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(220, 490, 210, 10);

        jSeparator3.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setBorder(null);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(220, 220, 210, 10);

        jSeparator4.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setBorder(null);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(220, 290, 210, 10);

        jSeparator5.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setBorder(null);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(220, 360, 210, 10);

        jSeparator6.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setBorder(null);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(220, 170, 210, 10);

        jSeparator7.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setBorder(null);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(220, 430, 210, 10);

        loginButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        loginButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonPanelMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 47, 65));
        jLabel4.setText("Save");

        javax.swing.GroupLayout loginButtonPanelLayout = new javax.swing.GroupLayout(loginButtonPanel);
        loginButtonPanel.setLayout(loginButtonPanelLayout);
        loginButtonPanelLayout.setHorizontalGroup(
            loginButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginButtonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        loginButtonPanelLayout.setVerticalGroup(
            loginButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel2.add(loginButtonPanel);
        loginButtonPanel.setBounds(510, 540, 90, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phoneActionPerformed

    private void jTextField_flatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_flatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_flatActionPerformed

    private void jTextField_pincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pincodeActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    private void loginButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonPanelMouseClicked
        Statement stmt;
        try {
            stmt = (Statement) conn.createStatement();
            String query = "update person set phone='"
                    + jTextField_phone.getText()
                    + "', email='" + jTextField_email.getText() + "', city='"
                    + jTextField_city.getText() + "', street='"
                    + jTextField_street.getText() + "', pincode='"
                    + jTextField_pincode.getText() + "' where p_id='" + pid + "'";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Profile Updated!");
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EditProfileJframe.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_loginButtonPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfileJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfileJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfileJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfileJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField_city;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_flat;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_pincode;
    private javax.swing.JTextField jTextField_street;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JPanel loginButtonPanel;
    // End of variables declaration//GEN-END:variables
}
