/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.viit.tnp.tpo;

import com.viit.tnp.common.MySqlConnect;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class CreateScheduleJframe extends javax.swing.JFrame {

    /**
     * Creates new form Schedule
     */
    int tpoId;
    int comp;
    String company;
    Connection conn = MySqlConnect.getConnection();
    
    public CreateScheduleJframe(int tpoId) {
        initComponents();
        setDefaultCloseOperation(CreateScheduleJframe.HIDE_ON_CLOSE);
        this.tpoId = tpoId;
        jLabelTpoId.setText(this.tpoId + "");
    }
    
    public void executeSQlQuery(String query, String message) {
        Statement st;
        try {
            st = conn.createStatement();
            if ((st.executeUpdate(query)) == 1) {
                JOptionPane.showMessageDialog(null, "Data " + message + " Succefully");
            } else {
                JOptionPane.showMessageDialog(null, "Data Not " + message);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        createButtonPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabelTpoId = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create schedule");

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Schedule Date : ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 70, 150, 22);
        jPanel3.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(290, 70, 120, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Minimum CGPA : ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 130, 160, 22);

        jTextField3.setBackground(new java.awt.Color(36, 47, 65));
        jTextField3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField3.setForeground(java.awt.Color.white);
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(290, 130, 210, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Academic Year : ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(50, 200, 149, 22);

        jComboBox1.setBackground(new java.awt.Color(36, 47, 65));
        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox1.setForeground(java.awt.Color.white);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jComboBox1.setBorder(null);
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(290, 200, 210, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Minimum Salary : ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(50, 260, 161, 22);

        jTextField5.setBackground(new java.awt.Color(36, 47, 65));
        jTextField5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField5.setForeground(java.awt.Color.white);
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField5);
        jTextField5.setBounds(290, 260, 210, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Company ID :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 310, 122, 22);

        jTextField6.setBackground(new java.awt.Color(36, 47, 65));
        jTextField6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField6.setForeground(java.awt.Color.white);
        jTextField6.setBorder(null);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(290, 310, 210, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TPO ID :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(50, 30, 75, 22);

        createButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        createButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonPanelMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 47, 65));
        jLabel11.setText("Create");

        javax.swing.GroupLayout createButtonPanelLayout = new javax.swing.GroupLayout(createButtonPanel);
        createButtonPanel.setLayout(createButtonPanelLayout);
        createButtonPanelLayout.setHorizontalGroup(
            createButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createButtonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        createButtonPanelLayout.setVerticalGroup(
            createButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel3.add(createButtonPanel);
        createButtonPanel.setBounds(200, 430, 110, 45);

        jLabelTpoId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelTpoId.setForeground(java.awt.Color.white);
        jLabelTpoId.setText("jLabel1");
        jPanel3.add(jLabelTpoId);
        jLabelTpoId.setBounds(290, 20, 90, 40);

        jSeparator2.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(null);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(290, 340, 210, 10);

        jSeparator3.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setBorder(null);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(290, 160, 210, 10);

        jSeparator4.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setBorder(null);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(290, 290, 210, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void createButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonPanelMouseClicked
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        
        String date = formater.format(dateChooserCombo1.getSelectedDate().getTime());
        String query1 = "INSERT INTO `schedule`(`criteria`,`min_salary`,"
                + "`sch_date`,`comp_id`,`tpo_id`,`acad_year`) VALUES ('"
                + jTextField3.getText() + "','" + jTextField5.getText() + "','"
                + date + "','" + jTextField6.getText() + "','"
                + tpoId + "','" + jComboBox1.getSelectedItem() + "')";
        
        boolean scheduleCreated = MySqlConnect.executeUpdateSQlQuery(query1);
        if (scheduleCreated) {
            JOptionPane.showMessageDialog(null, "Schedule created");
        } else {
            JOptionPane.showMessageDialog(null, "Schedule creation failed", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_createButtonPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel createButtonPanel;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTpoId;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel loginButtonPanel;
    private javax.swing.JPanel loginButtonPanel1;
    // End of variables declaration//GEN-END:variables
}
