/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.viit.tnp.tpo;

import com.viit.tnp.common.CommonUtils;
import com.viit.tnp.common.MySqlConnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class CreateScheduleJframe extends javax.swing.JFrame {

    /**
     * Creates new form Schedule
     */
    int tpoId;
    int comp;
    String company;
    Connection conn = MySqlConnect.getConnection();
    DefaultComboBoxModel comboModel;

    public CreateScheduleJframe(int tpoId) {
        getCompaniesList();
        initComponents();
        setDefaultCloseOperation(CreateScheduleJframe.HIDE_ON_CLOSE);
        this.tpoId = tpoId;
        jLabelTpoId.setText(this.tpoId + "");
        labelSalaryError.setVisible(false);
        labelMarksError.setVisible(false);
    }

    public void executeSQlQuery(String query, String message) {
        Statement st;
        try {
            st = conn.createStatement();
            if ((st.executeUpdate(query)) == 1) {
                JOptionPane.showMessageDialog(null, "Data " + message + " Succefully");
            } else {
                JOptionPane.showMessageDialog(null, "Data Not " + message);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMarks = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMinSalary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        createButtonPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabelTpoId = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        companyName = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        labelSalaryError = new javax.swing.JLabel();
        labelMarksError = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create schedule");

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Schedule Date : ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 70, 150, 22);
        jPanel3.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(290, 70, 120, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Minimum CGPA : ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 130, 160, 22);

        jTextFieldMarks.setBackground(new java.awt.Color(36, 47, 65));
        jTextFieldMarks.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldMarks.setForeground(java.awt.Color.white);
        jTextFieldMarks.setBorder(null);
        jTextFieldMarks.setCaretColor(java.awt.Color.white);
        jTextFieldMarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMarksKeyReleased(evt);
            }
        });
        jPanel3.add(jTextFieldMarks);
        jTextFieldMarks.setBounds(290, 130, 60, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Academic Year : ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(50, 200, 149, 22);

        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020" }));
        jComboBox1.setBorder(null);
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(290, 200, 210, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Minimum Salary : ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(50, 260, 161, 22);

        jTextFieldMinSalary.setBackground(new java.awt.Color(36, 47, 65));
        jTextFieldMinSalary.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldMinSalary.setForeground(java.awt.Color.white);
        jTextFieldMinSalary.setBorder(null);
        jTextFieldMinSalary.setCaretColor(java.awt.Color.white);
        jTextFieldMinSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMinSalaryKeyReleased(evt);
            }
        });
        jPanel3.add(jTextFieldMinSalary);
        jTextFieldMinSalary.setBounds(290, 260, 210, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Company :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 340, 96, 22);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TPO ID :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(50, 30, 75, 22);

        createButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        createButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonPanelMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 47, 65));
        jLabel11.setText("Create");

        javax.swing.GroupLayout createButtonPanelLayout = new javax.swing.GroupLayout(createButtonPanel);
        createButtonPanel.setLayout(createButtonPanelLayout);
        createButtonPanelLayout.setHorizontalGroup(
            createButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createButtonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        createButtonPanelLayout.setVerticalGroup(
            createButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel3.add(createButtonPanel);
        createButtonPanel.setBounds(200, 430, 110, 45);

        jLabelTpoId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelTpoId.setForeground(java.awt.Color.white);
        jLabelTpoId.setText("jLabel1");
        jPanel3.add(jLabelTpoId);
        jLabelTpoId.setBounds(290, 20, 90, 40);

        jSeparator3.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setBorder(null);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(290, 160, 60, 10);

        jSeparator4.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setBorder(null);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(290, 290, 210, 10);

        companyName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        companyName.setModel(comboModel);
        companyName.setBorder(null);
        jPanel3.add(companyName);
        companyName.setBounds(290, 340, 180, 32);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("/ 10");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(360, 130, 40, 30);

        labelSalaryError.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelSalaryError.setForeground(new java.awt.Color(230, 49, 29));
        labelSalaryError.setText("minSalaryError");
        jPanel3.add(labelSalaryError);
        labelSalaryError.setBounds(270, 300, 270, 21);

        labelMarksError.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelMarksError.setForeground(new java.awt.Color(230, 49, 29));
        labelMarksError.setText("marksError");
        jPanel3.add(labelMarksError);
        labelMarksError.setBounds(270, 170, 270, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void getCompaniesList() {

        String query1 = "select distinct(co_name) from company";

        Statement st;
        ResultSet rs;
        Vector companyNames = new Vector();

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query1);

            while (rs.next()) {
                companyNames.add(rs.getString("co_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        comboModel = new DefaultComboBoxModel(companyNames);
    }

    private void createSchedule() {
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");

        String date = formater.format(dateChooserCombo1.getSelectedDate().getTime());
        String query1 = "INSERT INTO `schedule`(`criteria`,`min_salary`,"
                + "`sch_date`,`comp_id`,`tpo_id`,`acad_year`) VALUES ('"
                + jTextFieldMarks.getText() + "','" + jTextFieldMinSalary.getText() + "','"
                + date + "','" + CommonUtils.getComapnyIdFromName(companyName.getSelectedItem().toString()) + "','"
                + tpoId + "','" + jComboBox1.getSelectedItem() + "')";

        boolean scheduleCreated = MySqlConnect.executeUpdateSQlQuery(query1);
        if (scheduleCreated) {
            JOptionPane.showMessageDialog(null, "Schedule created");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Schedule creation failed", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }
    private void createButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonPanelMouseClicked
        boolean isValidMarks = validateMarks();
        boolean isValidSalary = validateMinSalary();
        if (isValidMarks && isValidSalary) {
            createSchedule();
        }
    }//GEN-LAST:event_createButtonPanelMouseClicked

    boolean validateMarks() {
        boolean isValid = true;
        labelMarksError.setVisible(false);
        String marksText = jTextFieldMarks.getText();
        if (marksText.length() == 0) {
            isValid = false;
            labelMarksError.setText("Required");
            labelMarksError.setVisible(true);
        } else {
            try {
                float marks = Float.parseFloat(marksText);
                if (marks < 0 || marks > 10) {
                    labelMarksError.setText("Should be between 0 and 10");
                    labelMarksError.setVisible(true);
                }
            } catch (Exception e) {
                labelMarksError.setText("Should be a number");
                labelMarksError.setVisible(true);
            }
        }
        return isValid;
    }

    private boolean validateMinSalary() {
        boolean isValid = true;
        String salaryInput = jTextFieldMinSalary.getText();
        labelSalaryError.setVisible(false);
        if (salaryInput.length() != 0) {
            try {
                Integer.parseInt(salaryInput);
            } catch (Exception e) {
                isValid = false;
                labelSalaryError.setVisible(true);
                labelSalaryError.setText("Should be integer");
            }
        } else {
            isValid = false;
            labelSalaryError.setVisible(true);
            labelSalaryError.setText("Required");
        }
        return isValid;
    }
    private void jTextFieldMinSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMinSalaryKeyReleased
        validateMinSalary();
    }//GEN-LAST:event_jTextFieldMinSalaryKeyReleased

    private void jTextFieldMarksKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMarksKeyReleased
        validateMarks();
    }//GEN-LAST:event_jTextFieldMarksKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> companyName;
    private javax.swing.JPanel createButtonPanel;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTpoId;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldMarks;
    private javax.swing.JTextField jTextFieldMinSalary;
    private javax.swing.JLabel labelMarksError;
    private javax.swing.JLabel labelSalaryError;
    // End of variables declaration//GEN-END:variables
}
