/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.viit.tnp;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ali
 */
public class ScheduleRegistrationJFrame extends javax.swing.JFrame {

    Connection conn = MySqlConnect.getConnection();

    int stud_id;
    boolean isEligible = false;
    String scheduleDateString;

    public ScheduleRegistrationJFrame(Integer stu_id) {
        initComponents();
        setDefaultCloseOperation(ScheduleRegistrationJFrame.HIDE_ON_CLOSE);
        stud_id = stu_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        registrationTitleLabel = new javax.swing.JLabel();
        scheduleIdLabel = new javax.swing.JLabel();
        jTextField_sch_id = new javax.swing.JTextField();
        checkEligibility = new javax.swing.JButton();
        register = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        registrationTitleLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        registrationTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        registrationTitleLabel.setText("Registration");
        jPanel2.add(registrationTitleLabel);
        registrationTitleLabel.setBounds(140, 20, 180, 29);

        scheduleIdLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        scheduleIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        scheduleIdLabel.setText("Enter Schedule ID :");
        jPanel2.add(scheduleIdLabel);
        scheduleIdLabel.setBounds(30, 90, 151, 17);
        jPanel2.add(jTextField_sch_id);
        jTextField_sch_id.setBounds(250, 80, 145, 30);

        checkEligibility.setText("Check Eligibility");
        checkEligibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEligibilityActionPerformed(evt);
            }
        });
        jPanel2.add(checkEligibility);
        checkEligibility.setBounds(250, 120, 145, 34);

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel2.add(register);
        register.setBounds(120, 170, 180, 34);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, -150, 550, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkEligibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEligibilityActionPerformed
        int sch_id = Integer.parseInt(jTextField_sch_id.getText());
        PreparedStatement pst = null;
        ResultSet rs = null;
        CallableStatement cst = null;
        try {

//            Get schedule details
            String queryGetScheduleDetails = "SELECT criteria,sch_date from schedule where sch_id='" + sch_id + "'";
            pst = conn.prepareStatement(queryGetScheduleDetails);
            rs = pst.executeQuery(queryGetScheduleDetails);
            rs.next();
            int criteria = rs.getInt(1);
            scheduleDateString = rs.getDate(2).toString();          //taking the criteria of the schedule
            JOptionPane.showMessageDialog(null, "Your schedule criteria is : " + criteria);

//            Check whether student is eligible
            String callIsEligible = "{call IsEligible(?,?,?)}";
            cst = conn.prepareCall(callIsEligible);
            cst.setInt(1, stud_id);
            cst.setInt(2, criteria);
            cst.registerOutParameter(3, java.sql.Types.INTEGER);
            cst.execute();

            int valueReturnedFromProcedure = cst.getInt(3);

            if (valueReturnedFromProcedure == 1) {
                isEligible = true;
                JOptionPane.showMessageDialog(null, "You are eligible for the schedule");
            } else {
                isEligible = false;
                JOptionPane.showMessageDialog(null, "You're not eligible for the schedule!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ScheduleRegistrationJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_checkEligibilityActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        if (isEligible) {
            String query = "Insert into appearing(stu_id,sch_id,appearing_date) values('" + stud_id + "','" + jTextField_sch_id.getText() + "','" + scheduleDateString + "')";

            Statement st = null;
            try {
                st = conn.createStatement();
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Registration successful!");
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Unable to register", "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }

        } else {
            JOptionPane.showMessageDialog(null, "You're not eligible for the schedule!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Register_schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkEligibility;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_sch_id;
    private javax.swing.JButton register;
    private javax.swing.JLabel registrationTitleLabel;
    private javax.swing.JLabel scheduleIdLabel;
    // End of variables declaration//GEN-END:variables
}
