/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.viit.tnp.report;

import com.viit.tnp.common.MySqlConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class ReportCompanywiseJframe extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    String selectedYear = "";
    DefaultComboBoxModel comboModel;

    public ReportCompanywiseJframe() {
        getCompaniesList();
        initComponents();
        setDefaultCloseOperation(ReportCompanywiseJframe.HIDE_ON_CLOSE);
    }

    public void getCompaniesList() {

        String query1 = "select distinct(co_name) from company";

        Statement st;
        ResultSet rs;
        Vector companyNames = new Vector();

        try {
            st = MySqlConnect.getConnection().createStatement();
            rs = st.executeQuery(query1);

            while (rs.next()) {
                companyNames.add(rs.getString("co_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        comboModel = new DefaultComboBoxModel(companyNames);
    }

    public ArrayList<ReportStudentCountYear> getStudentList(String year) {
        ArrayList<ReportStudentCountYear> studentList = new ArrayList<ReportStudentCountYear>();
        Connection connection = MySqlConnect.getConnection();

        String yearQuery = "";

        Statement st;
        ResultSet rs = null;
        try {
            st = connection.createStatement();
            if (!year.equals("All")) {
                yearQuery = "and schedule.acad_year='" + year
                        + "'";

            }
            String query = "select count(cand_id),schedule_company_view.co_name"
                    + " from candidate,schedule,schedule_company_view "
                    + "where candidate.sch_id=schedule_company_view.sch_id "
                    + yearQuery + " and schedule.sch_id=schedule_company_view.sch_id "
                    + " group by schedule_company_view.co_name;";

            rs = st.executeQuery(query);

            ReportStudentCountYear user;
            while (rs.next()) {
                user = new ReportStudentCountYear(rs.getInt("count(cand_id)"),
                        rs.getString("schedule_company_view.co_name"));//

                studentList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return studentList;
    }

    public void showStudentsInJTable(String year) {
        ArrayList<ReportStudentCountYear> list1 = getStudentList(year);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        Object[] row = new Object[2];
        for (int i = 0; i < list1.size(); i++) {

            row[0] = list1.get(i).getStudentCount();
            row[1] = list1.get(i).getyear();

            model.addRow(row);
        }
    }

    /**
     * ***********************************************************************************
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboBoxYear = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_min = new javax.swing.JTextField();
        jTextField_max = new javax.swing.JTextField();
        comboBoxCompany = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_total = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Company statistics");

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(null);

        jTable1.setBackground(new java.awt.Color(36, 47, 65));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable1.setForeground(java.awt.Color.white);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total Students Recruited", "Company Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 90, 600, 80);

        comboBoxYear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        comboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "2016", "2017", "2018", "2019", "2020" }));
        comboBoxYear.setBorder(null);
        comboBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxYearActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxYear);
        comboBoxYear.setBounds(380, 40, 120, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Year : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 40, 90, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Min salary");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 340, 100, 22);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Max salary");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 340, 130, 22);

        jTextField_min.setEditable(false);
        jTextField_min.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_min.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_min.setForeground(java.awt.Color.white);
        jPanel1.add(jTextField_min);
        jTextField_min.setBounds(70, 390, 150, 30);

        jTextField_max.setEditable(false);
        jTextField_max.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_max.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_max.setForeground(java.awt.Color.white);
        jPanel1.add(jTextField_max);
        jTextField_max.setBounds(340, 390, 160, 30);

        comboBoxCompany.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        comboBoxCompany.setModel(comboModel);
        comboBoxCompany.setBorder(null);
        comboBoxCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCompanyActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxCompany);
        comboBoxCompany.setBounds(420, 270, 220, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Company :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 270, 130, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Department :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 620, 120, 17);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Recruits");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(570, 340, 160, 22);

        jTextField_total.setEditable(false);
        jTextField_total.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_total.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_total.setForeground(java.awt.Color.white);
        jPanel1.add(jTextField_total);
        jTextField_total.setBounds(570, 390, 140, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 210, 760, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxYearActionPerformed
        selectedYear = (comboBoxYear.getSelectedItem().toString());
        showStudentsInJTable(selectedYear);
    }//GEN-LAST:event_comboBoxYearActionPerformed

    public void showCompanyStats() {
        jTextField_min.setText("");
        jTextField_max.setText("");
        jTextField_total.setText("");

        String comp;
        comp = comboBoxCompany.getSelectedItem().toString();
        String query = "select min(package),max(package),count(cand_id)"
                + " from candidate,company,schedule_company_view where candidate.sch_id=schedule_company_view.sch_id "
                + "and company.comp_id=schedule_company_view.comp_id and company.co_name='" + comp
                + "'group by company.comp_id;";
        Connection conn = MySqlConnect.getConnection();
        PreparedStatement ps;
        try {
            ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jTextField_min.setText(rs.getString("min(package)").toString());
                jTextField_max.setText(rs.getString("max(package)").toString());
                jTextField_total.setText(rs.getString("count(cand_id)").toString());
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void comboBoxCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCompanyActionPerformed
        showCompanyStats();
    }//GEN-LAST:event_comboBoxCompanyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportCompanywiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportCompanywiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportCompanywiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportCompanywiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportCompanywiseJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxCompany;
    private javax.swing.JComboBox<String> comboBoxYear;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_max;
    private javax.swing.JTextField jTextField_min;
    private javax.swing.JTextField jTextField_total;
    // End of variables declaration//GEN-END:variables
}
