/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.viit.tnp.report;

import com.viit.tnp.common.MySqlConnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class ReportDepartmentWiseJframe extends javax.swing.JFrame {

    /**
     * Creates new form Report1
     */
    String dep;
    String year;
    DefaultComboBoxModel comboModel;
    public ReportDepartmentWiseJframe() {
        getDepartmentsList();
        initComponents();
        setDefaultCloseOperation(ReportDepartmentWiseJframe.HIDE_ON_CLOSE);
        jTable1.getTableHeader().setReorderingAllowed(false);
    }

    public void getDepartmentsList() {

        String query1 = "select distinct(dep_name) from department";

        Statement st;
        ResultSet rs;
        Vector depNames = new Vector();

        try {
            st = MySqlConnect.getConnection().createStatement();
            rs = st.executeQuery(query1);

            while (rs.next()) {
                depNames.add(rs.getString("dep_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        comboModel = new DefaultComboBoxModel(depNames);
    }
    public ArrayList<ReportStudentCountYear> getStudentList(String year, String dep) {
        ArrayList<ReportStudentCountYear> studentList = new ArrayList<ReportStudentCountYear>();
        Connection connection = MySqlConnect.getConnection();

        String query = "select count(cand_id),schedule_company_view.co_name from candidate,"
                + "schedule_company_view,department,TPO, schedule where candidate.sch_id=schedule_company_view.sch_id"
                + " and schedule_company_view.tpo_id=TPO.tpo_id "
                + "and TPO.d_id=department.d_id and dep_name='" 
                + dep + "'"
                + " and acad_year=" + year 
                + " and schedule.sch_id=schedule_company_view.sch_id group by schedule_company_view.co_name;";

        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();

            rs = st.executeQuery(query);

            ReportStudentCountYear user;
            while (rs.next()) {
                user = new ReportStudentCountYear(rs.getInt("count(cand_id)"), rs.getString("schedule_company_view.co_name"));//

                studentList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return studentList;
    }

    public void Show_Student_In_JTable(String dep, String year) {
        ArrayList<ReportStudentCountYear> list1 = getStudentList(dep, year);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        Object[] row = new Object[2];
        for (int i = 0; i < list1.size(); i++) {

            row[0] = list1.get(i).getStudentCount();
            row[1] = list1.get(i).getyear();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBoxDepartment = new javax.swing.JComboBox<>();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        showButtonPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Department statistics");

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(null);

        jComboBoxDepartment.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBoxDepartment.setModel(comboModel);
        jComboBoxDepartment.setBorder(null);
        jPanel2.add(jComboBoxDepartment);
        jComboBoxDepartment.setBounds(190, 50, 160, 30);

        jComboBoxYear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020" }));
        jComboBoxYear.setBorder(null);
        jPanel2.add(jComboBoxYear);
        jComboBoxYear.setBounds(410, 50, 100, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total Recruited Students", "Company Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(80, 200, 470, 100);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Department : ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 47, 130, 30);

        showButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        showButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showButtonPanelMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 47, 65));
        jLabel9.setText("Show");

        javax.swing.GroupLayout showButtonPanelLayout = new javax.swing.GroupLayout(showButtonPanel);
        showButtonPanel.setLayout(showButtonPanelLayout);
        showButtonPanelLayout.setHorizontalGroup(
            showButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showButtonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        showButtonPanelLayout.setVerticalGroup(
            showButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanel2.add(showButtonPanel);
        showButtonPanel.setBounds(270, 120, 99, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showButtonPanelMouseClicked
        dep = jComboBoxDepartment.getSelectedItem().toString();
        year = jComboBoxYear.getSelectedItem().toString();
        Show_Student_In_JTable(year, dep);
    }//GEN-LAST:event_showButtonPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDepartmentWiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDepartmentWiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDepartmentWiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDepartmentWiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportDepartmentWiseJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxDepartment;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel showButtonPanel;
    // End of variables declaration//GEN-END:variables
}
